name: authblocks
networks:
  authblocks-network:
    driver: bridge
volumes:
  authblocks-volume:
services:
  authblocks-database:
    image: mysql:latest
    container_name: authblocks-mysql
    environment:
      - MYSQL_DATABASE=authblocks
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    ports:
      - 3395:3306
    restart: unless-stopped
    volumes:
      - authblocks-volume:/var/lib/mysql
    networks:
      - authblocks-network
